###########################
# Main configuration file #
###########################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
group: !include groups.yaml
logger: !include logger.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
